language: ruby
bundler_args: --without development
before_install: "sudo apt-get install -y libvirt-ruby libvirt-dev"

rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  # - rbx-19mode # currently in active development, may or may not work for your project
# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec
branches:
  only:
    - develop
notifications:
  irc: "irc.freenode.org#theforeman"
